CHK-328: Add addToCart and removeFromCart pixel events on product list
vtex-apps/checkout-cart pull request #63
Opened 2020-09-10 18:21 UTC by lucasecdb

#### What problem is this solving?

Adds the events of `addToCart` when you change the product quantity and `removeFromCart` when you remove a product.

#### How to test it?

[Workspace](https://lucas--checkoutio.myvtex.com/cart/add?sku=289).

You can test by editing or removing the item and seeing if `window.dataLayer` contains the `addToCart` and/or `removeFromCart` events properly registered.

#### Screenshots or example usage:

N/A

#### Describe alternatives you've considered, if any.

N/A

#### Related to / Depends on

N/A

2020-09-10 18:51 UTC, klzns requested changes

2020-09-10 18:51 UTC, klzns commented on react/utils/pixel.ts
> +    referenceId: item.refId ?? '',
Recently we added seller and sellerName

https://github.com/vtex-apps/add-to-cart-button/pull/47/files

2020-09-10 18:55 UTC, lucasecdb commented on react/utils/pixel.ts
> +    referenceId: item.refId ?? '',
but the item doesn't have `sellerName`: https://github.com/vtex/checkout-graphql/blob/master/graphql/types/Item.graphql#L24

2020-09-10 20:34 UTC, klzns approved these changes

2020-09-14 13:59 UTC, darlenedms approved these changes

2020-09-14 14:36 UTC, merged