Use navigate when redirecting to checkout
vtex-apps/checkout-cart pull request #67
Opened 2020-09-29 19:56 UTC by vitorflg

#### What problem is this solving?

Use navigate when redirecting to checkout cart to permit adding the loading bar on top of the document.

#### How to test it?

In the workspace try to add to cart and verify if everything is ok( with the redirect) and if the document has a loading bar in the process.

https://vitorflg--gc-jqu0734.myvtex.com/

#### Screenshots or example usage:

X

#### Describe alternatives you've considered, if any.

X

#### Related to / Depends on

https://github.com/vtex-apps/render-runtime/pull/567

2020-09-29 19:58 UTC, klzns requested changes
Missing changelog, as pointed by danger

2020-09-29 20:12 UTC, klzns requested changes
Rebase branch and push force so the merge commits gets removed

2020-09-29 20:12 UTC, klzns commented on CHANGELOG.md
> +
```suggestion
```

2020-09-29 20:12 UTC, klzns commented on CHANGELOG.md
> +
```suggestion
```

2020-09-29 20:18 UTC, lucasecdb commented on react/GoToCheckout.tsx
> +      })
why do you need to use navigate?

2020-09-29 20:19 UTC, klzns commented on react/GoToCheckout.tsx
> +      })
![image](https://user-images.githubusercontent.com/284515/94611312-f03faa00-0277-11eb-9f2b-79a75193beb1.png)

2020-09-29 20:19 UTC, lucasecdb commented on react/GoToCheckout.tsx
> +      })
is it just for the loading bar?

2020-09-29 20:25 UTC, klzns commented on react/GoToCheckout.tsx
> +      })
Yess. Right, @vitorflg?

2020-09-29 20:38 UTC, vitorflg commented on react/GoToCheckout.tsx
> +      })
Yes

2020-10-01 18:56 UTC, klzns approved these changes

2020-10-01 19:09 UTC, lucasecdb approved these changes

2020-10-01 20:01 UTC, icazevedo approved these changes

2020-10-13 20:50 UTC, merged